### ISSUE TITLE
it doese't work on my server

### ISSUE THREAD

**Issue by LifeNT** [beakerbrowser/dathttpd#26] opened 2018-01-02 01:40 UTC
I run dathttpd on my vps, but got a ERR_CONNECTION_CLOSED when I visit my site by https, and got a 404 error when I use dat://, and where is the log?

the console seems all right:
![img20180102094327](https://user-images.githubusercontent.com/7828213/34472661-9cba056a-efa1-11e7-9055-e90bb5911437.jpg)

but the site with https is this:
![3](https://user-images.githubusercontent.com/7828213/34474186-9f752194-efb6-11e7-8d39-dcf0ecf7bee8.PNG)

and it's "404 No DNS record found " for dat://mydomain
![default](https://user-images.githubusercontent.com/7828213/34490149-e1d948fe-f019-11e7-9b6c-69504567cfcd.PNG)

**Comment by pfrazee** [comment] 2018-01-02 16:40
What domain name are you using? Do you have the domain name mapped to your server's IP?

**Comment by LifeNT** [comment] 2018-01-03 13:28
yes，I have a domain， and I checked all ports :80, 443, 3282 are open, the server has got all files by DAT, from my beaker on pc, but I can't got it from my server through beaker

**Comment by pfrazee** [comment] 2018-01-03 17:05
Yeah if you turn of lets encrypt, the http version will work, but you can't use a dat shortname because it depends on https being used.

It's interesting that you hit the rate limit. Are you using the latest version of dathttpd?

**Comment by LifeNT** [comment] 2018-01-04 00:12
I'm using the dathttpd 3.2 by yum install, I change to a subdomain, then I got these:
[pyconf] WARN index past array length:
68 68 undefined
unexpected duplicate key 'keyPath': '/root/letsencrypt/etc/live/dat.lifent.xyz/privkey.pem'
unexpected duplicate key 'checkpoints': '0'      unexpected duplicate key 'account':

**Comment by LifeNT** [comment] 2018-01-04 00:22
I checked letsencrypt dir, I have these:cert.pem   fullchain.pem  privkey.pem.bak
chain.pem  privkey.pem
did I miss something?

**Comment by LifeNT** [comment] 2018-01-04 06:07
by the way, if port 3282 blocked, we can't get access to dat

**Comment by LifeNT** [comment] 2018-01-04 12:55
I tried install dathttpd on debian 8.5 x64 , with node js 8.9.4, it's the same result: not work with https

**Comment by pfrazee** [comment] 2018-01-04 22:22
Ok I'm reproducing a lot of these issues. Will let you know what I find.

**Comment by pfrazee** [comment] 2018-01-04 22:43
I found a bug in the domain approval, which I solved and that caused everything to work. You were also correct that the port `3282` needed to be opened. I added that instruction to the readme.

Try version `3.2.1` and let me know how it goes.

**Comment by LifeNT** [comment] 2018-01-05 00:11
yes，congratulations！https works now。

**Comment by pfrazee** [comment] 2018-01-05 00:14
Good deal! Sorry for the amount of trouble you had! Closing. Feel free to reopen or open a new issue if you need to.

**Closed by pfrazee** 2018-01-05 00:14 UTC
